<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Testriqs-MacBook-Air-5.local" failures="1" tests="2" name="UploadTest" time="148.211" errors="0" timestamp="11 Jan 2025 12:37:32 GMT">
  <testcase classname="Demo.Invoify.tests.verifyAttachmentUpload" name="testSignatureUpload" time="73.097"/>
  <testcase classname="Demo.Invoify.tests.verifyAttachmentUpload" name="verifyBillAttachement" time="37.821">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at Demo.Invoify.tests.verifyAttachmentUpload.verifyBillAttachement(verifyAttachmentUpload.java:25)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- verifyBillAttachement -->
</testsuite> <!-- UploadTest -->
